version: '3.8'

networks:
    docker-network:

services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./data/mongodb:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        networks:
            - docker-network
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
        container_name: elasticsearch
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        volumes:
            - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - docker-network
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.16.1
        container_name: kibana
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            - docker-network
        volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml

    
    elasticsearch6:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
        container_name: elasticsearch6
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        volumes:
            - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - docker-network
    
    kibana6:
        image: docker.elastic.co/kibana/kibana:6.8.3
        container_name: kibana6
        depends_on:
            - elasticsearch6
        ports:
            - 5601:5601
        networks:
            - docker-network
        volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    